GET http://localhost:3000/api/users/superUser/create
Accept: application/json
content-type: application/json
###
GET http://localhost:3000/api/users/superUser/turnSuperUser
Accept: application/json
content-type: application/json
###