POST http://localhost:3000/api/users/createUser
Accept: application/json
content-type: application/json

{
  "name": "Alice",
  "password": "Alice"
}
###
POST http://localhost:3000/api/users/createUser
Accept: application/json
content-type: application/json

{
  "name": "Mig",
  "password": "Mig",
  "superUser": true
}
###
POST http://localhost:3000/api/users/createUser
Accept: application/json
content-type: application/json

{
  "name": "a",
  "password": "a",
  "superUser": true
}
###
POST http://localhost:3000/api/users/createUser
Accept: application/json
content-type: application/json

{
  "name": "b",
  "password": "b",
  "superUser": true
}
###
PUT http://localhost:3000/api/users/modifyMig
Accept: application/json
content-type: application/json

{
  "superUser": true
}
###
GET http://localhost:3000/api/users/getUsers
Content-Type: application/json